; LC3 Program that Displayes
; "HELLO WORLD " to the console 
;CLASS: CSE 313 MACHINE ORG LAB 
;SECTION 02 
;INSTRUCTOR: TALINE GEORGIOU
;TERM: (FALL 2018) 
;NAME: AUDREY CARDS, YOUSEF JARRAR
;LAB#0: PARTS OF AN LC-3 PROGRAM 
; DESCRIPTION: THIS PROGRAM IS AN INTRODUCTION TO LEARNING THE PARTS 
; OF LC-3. 



	.ORIG x3000
	LEA R0, HW  ;Load address to String 
	PUTS		;Output String to Console
 	HALT		;END PROGRAM
HW	.STRINGZ "Hello World!"
	.END