;Class: CSE 313 Machine Organization Lab
;Term: Fall 2018
;Name(s): Yousef Jarrar, Audrey Cards
;Lab#7: Computing Days of the week
;Description: This program takes the day, month, and year to come up with a day of the week that 
;specific day lands on. 	

.ORIG x3000
	LDI R3, M 		;R3 LOADS MONTH	
	LDI R4, Y           	;R4 LOADS YEAR	
	ADD R0, R0, R3		;		
	JSR MONTH		;JMP INTO MONTH_SUBROUTINE
	ST R0, SAVEREG		;STORE R0 (M)	

	AND R0, R0, #0		;
	ADD R0, R0, R4		;ADDING R4 TO R0
	JSR SEPERATE	
	ST R1, SAVEREG1		;STORE R1 (CENTURY)	
	ST R0, SAVEREG2		;STORE R0 (YEAR)	
		
	LD R0, SAVEREG		;LOAD R0	
	ADD R0, R0, #1		;ADD R0 & 1 -- STORE R0	
	AND R1, R1, #0		;
	ADD R1, R1, #13		;
	AND R2, R2, #0		;	
			
	JSR MULT		;JMP TO MULTIPLY_SUBROUTINE	
	AND R0, R0, #0		;
	AND R1, R1, #0		;
	ADD R0, R0, R2  	;	
	ADD R1, R1, #5		;
	NOT R1, R1		;
	ADD R1, R1, #1		;2'S COMPLIMENT 
	AND R2, R2, #0		;
			
	JSR DIV			;JMP TO DIVISON_SUBROUTINE		
      

	LDI R0, K		;K LOADED INTO R0 	
	ADD R6, R0, R2		;	
    
	LD R0, SAVEREG2		;SAVE R0			
	ADD R6, R6, R0		;CALCULATE D/4

	AND R1, R1, #0		;CHECKING R1	
	ADD R1, R1, #4		;ADD #4 	
	AND R2, R2, #0		;	
	NOT R1, R1		;
	ADD R1, R1, #1		;2'S COMPLEMENT
	JSR DIV			;JMP TO DIVISION_SUBROUTINE 		
	

	

	ADD R6, R6, R2		;
	LD R0, SAVEREG1		;LOADING SAVE REGISTERS 	
	AND R1, R1, #0		;
	ADD R1, R1, #2		;
	AND R2, R2, #0		;
	JSR MULT		;JMP TO MULTIPLY_SUBROUTINE 

	NOT R2, R2		;
	ADD R2, R2, #1		;2'S COMPLEMENT
	ADD R6, R6, R2		;

	AND R1, R1, #0		;
	ADD R1, R1, #4		;
	NOT R1, R1		;
	ADD R1, R1, #1		;2'S COMPLEMENT
	AND R2, R2, #0		;
	JSR DIV			;JMP TO DIVISION_SUBROUTINE   
			
			
	ADD R6, R6, R2		;
	AND R0, R0, #0		;
	AND R1, R1, #0		;
	AND R2, R2, #0		;
	ADD R0, R0, R6		;
	ADD R1, R1, #7		;
	NOT R1, R1		;
	ADD R1, R1, #1		;2'S COMPLEMENT
	JSR DIV			;JMP TO DIVISION_SUBROUTINE		

	ADD R3, R0, #0		;
	STI R3, FINAL		;R3 SAVED INTO LABEL 'FINAL'		
	LEA R0, DAYS		;
	
	LOOPS	ADD R3, R3, #0	;CHECK R3
		BRz PRINT	;IF ZERO BRANCH TO PRINT
		ADD R0, R0, #10	;ADD 10 TO R0
		ADD R3, R3, #-1	;DECREMENT R3
		BR LOOPS	;LOOP THROUGH AGAIN
	PRINT	PUTS		;PRINTS DAY TO SCREEN
		
	HALT
	
MONTH	ADD R0, R0, #-2	;ADDING -2 TO MONTH TO CHECK	
	BRnz	MONTH1	;IF NEGATIVE OR ZERO JUMP TO MONTH1	
	BRp	MONTH2	;IF POSITIVE JUMP TO MONTH2	
	
MONTH1	ADD R0, R0, #14	;FORMULA GIVEN IN LAB MANUAL	
	ADD R4, R4, #-1
	RET
		
MONTH2	ADD R0, R0, #2	;ADDS 2 TO GET BACK TO ORIGINAL INPUT	
	RET
	

SEPERATE	
		AND R3, R3, x0		
		ADD R3, R3, #15
		ADD R3, R3, #15
		ADD R3, R3, #15
		ADD R3, R3, #15
		ADD R3, R3, #15
		ADD R3, R3, #15
		ADD R3, R3, #10
			
		NOT R3, R3	
		ADD R3, R3, #1
		AND R2, R2, #0		;REMAINDER		
		AND R1, R1, #0		;QUOTIENT				
		BR SEPLOOP
	
	
SEPLOOP		ADD R0, R0, R3		;ADDING R0 TO R3 AND STORING IN R8	
		BRnz SEPEND		;ONCE ZERO OR NEGATIVE THE LOOP ENDS	
		ADD R1, R1, #1		;INCREMENTING R1		
		BR SEPLOOP		;KEEP LOOPING
	

SEPEND	NOT R3, R3		;NEGATING R3
	ADD R3, R3, #1		;2'S COMPLEMENT
	ADD R0, R0, R3		;
			
	ADD R2, R0, R3		;	
		
	RET			;RETURN FROM SUBROUTINE
	

	MULT	ADD R2, R2, R0	;
		ADD R1, R1, #-1	;
		BRz RETURN	;IF R1 IS ZERO JUMP TO RETURN
		BR MULT		;OTHERWISE LOOP THROUGH AGAIN
			
	DIV	ADD R0, R0, R1	;
		ADD R2, R2, #1	;COMPARE X AND Y
			
		AND R3, R3, #0	;
		ADD R3, R0, R1	;
		BRn RETURN	;IF NEGATIVE RETURN FROM SUBROUTINE
		BR DIV		;OTHERWISE BRANCH AND LOOP AGAIN	
	

	RETURN 	 RET
	

	

	

	K	.FILL x31F0		;THE DAY INTO x31F0
	M	.FILL x31F1		;THE MONTH INTO x31F1
	Y	.FILL x31F2		;THE YEAR INTO x31F2
	FINAL	.FILL x31F3		;THE ANSWER INTO x31F3
	SAVEREG	.FILL x0				
	SAVEREG1 .FILL x0			
	SAVEREG2 .FILL x0			

	DAYS	
		.STRINGZ "Saturday "
		.STRINGZ "Sunday   "
		.STRINGZ "Monday   "	
		.STRINGZ "Tuesday  "
		.STRINGZ "Wednesday"
		.STRINGZ "Thursday "
		.STRINGZ "Friday   "

	.END 

